# Generated by Django 3.2.25 on 2025-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_investment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='home_invest_user_id_572b54_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_type'], name='home_invest_investm_cb8a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['purchase_date'], name='home_invest_purchas_92b07f_idx'),
        ),
    ]
