# Generated by Django 5.2.1 on 2025-06-10 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250610_2111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='stock_symbol',
            field=models.CharField(blank=True, help_text='Stock symbol for real-time tracking (e.g., AAPL)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['stock_symbol'], name='home_invest_stock_s_e96dac_idx'),
        ),
    ]
