# Generated by Django 5.2.1 on 2025-06-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_addmoney_info_id_alter_budget_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoney_info',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.investment'),
        ),
    ]
